### ISSUE TITLE
Надо добавить цвет фона к #layout для совместимости с другими темами

### ISSUE THREAD

**Issue by omgiafs** [WaveCutz/habrahabr.ru_night-mode#10]
Для совместимости с другими темами, например http://userstyles.org/styles/101529/new-habr-clean,
следует с 27 строки изменить

``` css
#layout
{
  position: relative;
}
```

на

``` css
#layout
{
  position: relative;
  background-color: rgb(51, 51, 51) !important;
}
```

Пул-реквесты не осилил :)
